# Generated by Django 4.2.4 on 2024-04-20 09:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('da_ti', models.DateTimeField(auto_now=True)),
                ('dis', models.CharField(blank=True, max_length=240, null=True)),
                ('file', models.FileField(max_length=100000, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpeg', 'jpg'])])),
                ('auname', models.CharField(default='name', max_length=30)),
                ('author', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('da_ti', models.DateTimeField(auto_now=True)),
                ('dis', models.CharField(blank=True, max_length=240, null=True)),
                ('file', models.FileField(max_length=100000, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpeg', 'jpg'])])),
                ('auname', models.CharField(default='name', max_length=30)),
                ('author', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_fourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('da_ti', models.DateTimeField(auto_now=True)),
                ('dis', models.CharField(blank=True, max_length=240, null=True)),
                ('file', models.FileField(max_length=100000, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpeg', 'jpg'])])),
                ('auname', models.CharField(default='name', max_length=30)),
                ('author', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('dis', models.CharField(blank=True, max_length=240, null=True)),
                ('da_ti', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=100000, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'jpeg'])])),
                ('auname', models.CharField(default='name', max_length=30)),
                ('author', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
