# Generated by Django 4.2.4 on 2024-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noto_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='bugs'),
        ),
    ]
